[package]
name = "deadreckon-runtime"
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
chrono.workspace = true
deadreckon-core = { workspace = true }
deadreckon-protocol = { workspace = true }
deadreckon-providers = { workspace = true }
deadreckon-sandbox = { workspace = true }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tempfile.workspace = true
tokio-util.workspace = true
toml.workspace = true

[dev-dependencies]
