use std::collections::VecDeque;
use std::sync::Mutex;

use serde_json::json;

use crate::{
    Provider, ProviderError, ProviderFuture, ProviderKind, ProviderRequest, ProviderResponse,
    ProviderUsage, SpendEstimate,
};

pub(crate) struct ScriptedSmokeProvider {
    responses: Mutex<VecDeque<String>>,
}

impl ScriptedSmokeProvider {
    pub(crate) fn new() -> Self {
        Self {
            responses: Mutex::new(VecDeque::from([
                json!({
                    "action": "bash",
                    "tool_call_id": "smoke-bash-1",
                    "command": "mkdir -p src\nprintf '[package]\\nname = \"working\"\\nversion = \"0.1.0\"\\nedition = \"2024\"\\n\\n[dependencies]\\n\\n[workspace]\\n' > Cargo.toml\nprintf 'fn main() {\\n    println!(\"hello from deadreckon\");\\n}\\n' > src/main.rs\ncargo test --manifest-path Cargo.toml"
                })
                .to_string(),
                json!({
                    "action": "write_file",
                    "tool_call_id": "smoke-write-2",
                    "path": "README.md",
                    "content": "# tiny hello rust\n\nGenerated by deadreckon --smoke.\n"
                })
                .to_string(),
                json!({
                    "action": "done",
                    "summary": "tiny Rust project created"
                })
                .to_string(),
            ])),
        }
    }
}

impl Provider for ScriptedSmokeProvider {
    fn name(&self) -> &str {
        "smoke"
    }

    fn kind(&self) -> ProviderKind {
        ProviderKind::ScriptedSmoke
    }

    fn model(&self) -> &str {
        "local-scripted-smoke"
    }

    fn has_credential(&self) -> bool {
        true
    }

    fn estimate_spend(&self, usage: ProviderUsage) -> SpendEstimate {
        SpendEstimate {
            provider: self.name().to_string(),
            model: self.model().to_string(),
            input_tokens: usage.input_tokens,
            output_tokens: usage.output_tokens,
            cost_usd: 0.0,
            subscription: false,
            wall_time_seconds: None,
        }
    }

    fn complete<'a>(&'a self, request: &'a ProviderRequest) -> ProviderFuture<'a> {
        Box::pin(async move {
            let (content, remaining_steps) = {
                let mut responses = self.responses.lock().map_err(|_| ProviderError::Cli {
                    provider: self.name().to_string(),
                    detail: "scripted provider lock poisoned".to_string(),
                })?;
                let content = responses.pop_front().unwrap_or_else(|| {
                    json!({
                        "action": "done",
                        "summary": "script exhausted"
                    })
                    .to_string()
                });
                (content, responses.len())
            };
            let usage = ProviderUsage {
                input_tokens: (request.prompt.len() / 4) as u64,
                output_tokens: (content.len() / 4) as u64,
            };
            Ok(ProviderResponse {
                provider: self.name().to_string(),
                model: self.model().to_string(),
                content,
                usage: usage.clone(),
                spend: self.estimate_spend(usage),
                trace: json!({
                    "kind": "scripted_smoke",
                    "remaining_steps": remaining_steps,
                }),
            })
        })
    }
}
