use std::collections::VecDeque;
use std::sync::Mutex;

use deadreckon_sandbox::WorkspaceAccess;
use serde_json::json;

use crate::{
    Provider, ProviderError, ProviderFuture, ProviderKind, ProviderRequest, ProviderResponse,
    ProviderUsage, SpendEstimate,
};

pub(crate) struct ScriptedSmokeProvider {
    responses: Mutex<VecDeque<String>>,
}

impl ScriptedSmokeProvider {
    pub(crate) fn new() -> Self {
        Self {
            responses: Mutex::new(VecDeque::from([
                json!({
                    "action": "bash",
                    "tool_call_id": "smoke-bash-1",
                    "command": "mkdir -p src\nprintf '[package]\\nname = \"working\"\\nversion = \"0.1.0\"\\nedition = \"2024\"\\n\\n[dependencies]\\n\\n[workspace]\\n' > Cargo.toml\nprintf 'fn main() {\\n    println!(\"hello from deadreckon\");\\n}\\n' > src/main.rs\nprintf '<!doctype html>\\n<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Implementation notes</title></head><body><h1>Implementation notes</h1><section id=\"design-decisions\"><h2>Design decisions</h2><p>Use a tiny Rust binary as the smoke artifact.</p></section><section id=\"deviations\"><h2>Deviations</h2><p>None.</p></section><section id=\"tradeoffs\"><h2>Tradeoffs</h2><p>Keep the smoke project minimal instead of adding dependencies.</p></section><section id=\"open-questions\"><h2>Open questions</h2><p>None.</p></section></body></html>\\n' > implementation-notes.html\ncargo test --manifest-path Cargo.toml"
                })
                .to_string(),
                json!({
                    "action": "bash",
                    "tool_call_id": "smoke-bash-2",
                    "command": "printf '# tiny hello rust\\n\\nGenerated by deadreckon --smoke.\\n' > README.md\nprintf '<!doctype html>\\n<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Implementation notes</title></head><body><h1>Implementation notes</h1><section id=\"design-decisions\"><h2>Design decisions</h2><p>Use a tiny Rust binary as the smoke artifact.</p></section><section id=\"deviations\"><h2>Deviations</h2><p>None.</p></section><section id=\"tradeoffs\"><h2>Tradeoffs</h2><p>Keep the smoke project minimal instead of adding dependencies.</p></section><section id=\"open-questions\"><h2>Open questions</h2><p>None after adding README.</p></section></body></html>\\n' > implementation-notes.html"
                })
                .to_string(),
                json!({
                    "action": "done",
                    "summary": "tiny Rust project created"
                })
                .to_string(),
            ])),
        }
    }
}

impl Provider for ScriptedSmokeProvider {
    fn name(&self) -> &str {
        "smoke"
    }

    fn kind(&self) -> ProviderKind {
        ProviderKind::ScriptedSmoke
    }

    fn model(&self) -> &str {
        "local-scripted-smoke"
    }

    fn has_credential(&self) -> bool {
        true
    }

    fn estimate_spend(&self, usage: ProviderUsage) -> SpendEstimate {
        SpendEstimate {
            provider: self.name().to_string(),
            model: self.model().to_string(),
            input_tokens: usage.input_tokens,
            output_tokens: usage.output_tokens,
            cost_usd: 0.0,
            subscription: false,
            wall_time_seconds: None,
        }
    }

    fn complete<'a>(&'a self, request: &'a ProviderRequest) -> ProviderFuture<'a> {
        Box::pin(async move {
            if request.workspace_access == WorkspaceAccess::ReadOnly
                && request.output_schema.is_some()
            {
                let content = json!({
                    "decision": "achieved",
                    "summary": "the deterministic smoke result satisfies the approved fixture goal",
                    "goal_coverage": [{
                        "claim": "approved smoke goal",
                        "status": "met",
                        "evidence": [
                            "approved-goal",
                            "approved-contract",
                            "source-diff",
                            "deterministic-gate"
                        ]
                    }],
                    "missing": []
                })
                .to_string();
                let usage = ProviderUsage {
                    input_tokens: (request.prompt.len() / 4) as u64,
                    output_tokens: (content.len() / 4) as u64,
                };
                return Ok(ProviderResponse {
                    provider: self.name().to_string(),
                    model: self.model().to_string(),
                    content,
                    usage: usage.clone(),
                    spend: self.estimate_spend(usage),
                    trace: json!({
                        "kind": "scripted_smoke_semantic_judge",
                        "workspace_access": "read_only",
                        "session": false,
                    }),
                });
            }
            let (content, remaining_steps) = {
                let mut responses = self.responses.lock().map_err(|_| ProviderError::Cli {
                    provider: self.name().to_string(),
                    detail: "scripted provider lock poisoned".to_string(),
                })?;
                let content = responses.pop_front().unwrap_or_else(|| {
                    json!({
                        "action": "done",
                        "summary": "script exhausted"
                    })
                    .to_string()
                });
                (content, responses.len())
            };
            let usage = ProviderUsage {
                input_tokens: (request.prompt.len() / 4) as u64,
                output_tokens: (content.len() / 4) as u64,
            };
            Ok(ProviderResponse {
                provider: self.name().to_string(),
                model: self.model().to_string(),
                content,
                usage: usage.clone(),
                spend: self.estimate_spend(usage),
                trace: json!({
                    "kind": "scripted_smoke",
                    "remaining_steps": remaining_steps,
                }),
            })
        })
    }
}

#[cfg(test)]
mod tests {
    use deadreckon_sandbox::WorkspaceAccess;

    use super::*;

    #[tokio::test]
    async fn semantic_smoke_response_is_read_only_and_does_not_consume_worker_steps() {
        let provider = ScriptedSmokeProvider::new();
        let semantic = provider
            .complete(&ProviderRequest {
                workspace_access: WorkspaceAccess::ReadOnly,
                output_schema: Some(json!({ "type": "object" })),
                ..ProviderRequest::default()
            })
            .await
            .expect("semantic response");
        assert!(semantic.content.contains("\"decision\":\"achieved\""));
        assert_eq!(semantic.trace["workspace_access"], "read_only");

        let worker = provider
            .complete(&ProviderRequest::default())
            .await
            .expect("worker response");
        assert!(worker.content.contains("\"tool_call_id\":\"smoke-bash-1\""));
    }
}
