[package]
name = "deadreckon-providers"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
deadreckon-sandbox = { path = "../deadreckon-sandbox" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
which.workspace = true

[dev-dependencies]
axum.workspace = true
tempfile.workspace = true
